name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Deploy on push to the main branch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18' # Adjust Node.js version if needed

    - name: Install dependencies
      run: npm install

    - name: Build project
      run: npm run build  # This will automatically generate the `out` directory based on next.config.mjs

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./out  # This is the directory containing your static files
